name: ResourcePackPlugin
version: 1.0
main: com.example.resourcepackplugin.ResourcePackPlugin
description: A plugin that loads a custom resource pack.
commands:
  loadpack:
    description: Load a resource pack
    resource-pack-url: "https://blocktopolis.redirectme.net/uploads/Redbull.zip"
    usage: /loadpack
    permission: resourcepack.load
